
from .implementation_scalaire.compute_scalar import ScalarComputationEngine
from .implementation_vectorielle.compute_numpy import VectorComputationEngine
from .implementation_gpu.compute_gpu import GPUComputationEngine
